# Generated by Django 4.0.3 on 2022-04-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_wafdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iptableRules',
        ),
        migrations.RemoveField(
            model_name='ons',
            name='question',
        ),
        migrations.DeleteModel(
            name='wafdetails',
        ),
        migrations.DeleteModel(
            name='ons',
        ),
        migrations.DeleteModel(
            name='sgn',
        ),
    ]
